# Identity
spring.application.name=discovery-service

# Disable Config Server search for Eureka itself
spring.cloud.config.enabled=false

# Local Eureka Port
server.port=8761

# Server Configuration
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false