# Port
server.port=8888

# Identity
spring.application.name=config-server

# GIT MODE
spring.profiles.active=git
spring.cloud.config.server.git.uri=file:///config-repo

# EUREKA CLIENT
eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka/